services:
  db:
    image: postgres:16.8
    container_name: avito-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MyPostgresPassword
      POSTGRES_DB: pvz-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pvz-db"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

  pvz-api:
      build: .
      container_name: avito-backend
      ports:
        - "8080:8080"
        - "3000:3000"
      environment:
        - DATABASE_PORT=5432
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=MyPostgresPassword
        - DATABASE_NAME=pvz-db
        - DATABASE_HOST=db
        - HTTP_PORT=8080
        - GRPC_PORT=3000
        - JWT_SECRET=MyJWTSecret
        - CONFIG_PATH=./configs/prod.yaml
      depends_on:
        db:
            condition: service_healthy
      networks:
        - internal
  
  
networks:
  internal:

volumes:
  postgres_data: